dist: trusty
sudo: required

language: scala

env:
  - JAVA_OPTS="-DSKIP_FLAKY=true -Dsbt.log.noformat=true"

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
   - $HOME/.dodo

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

before_install:
  - mkdir -p $HOME/.sbt/1.0/plugins
  - echo 'addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.1")' > $HOME/.sbt/1.0/plugins/gpg.sbt
  - openssl aes-256-cbc -K $encrypted_0c03606c72ea_key -iv $encrypted_0c03606c72ea_iv -in sonatype.sbt.enc -out $HOME/.sbt/1.0/sonatype.sbt -d

scala:
  - 2.11.12
  - 2.12.6

jdk:
  - oraclejdk8

notifications:
  slack:
    secure: BFX2aB0sq5cMxmxlWIwgHwJOjI5W6WBn3YSPqHYYz6VAK6fzlX2VUKsfyQJTUnqMYox/0qGzPUB4TFhVMH3c78ocNZNj/9tPOPLkMfHjAqobnq/89+hp4Q6fmWCMKVAGTzVNq83OCykYkzITcYWxo0Pyc2eguW6tHaHIgqnbCRY=

before_script:
  - unset SBT_OPTS # default $SBT_OPTS is irrelevant to sbt launcher

script:
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - if [[ "$TRAVIS_SCALA_VERSION" == 2.11* ]]; then travis_retry ./sbt ++$TRAVIS_SCALA_VERSION "project util-intellij" coverage test coverageReport; fi

after_success:
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - bash <(curl -s https://codecov.io/bash)

stages:
  - test
  - name: publish-snapshot
    if: env(TRAVIS_EVENT_TYPE) = cron

jobs:
  include:
    - stage: publish-snapshot
      script: ./sbt +publishLocal +publishLocalSigned +publishSigned +publishM2
      script: ./sbt "project util-intellij" +publishSigned
